apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: lukepolo/hello-world:node
        name: hello-world

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP  
  ports:
  - name: "hello-world"
    port: 3000
  selector:
    app: hello-world


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.codepier
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 3000
